language: java

dist: trusty

addons:
  apt:
    packages:
      - desktop-file-utils

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

script:
  - ant all
  - desktop-file-validate src/etc/net.sf.portecle.desktop
